server:
  port: 8091
spring:
  cloud:
      config:
        uri:
        - localhost:8888
        name: asso
        profile: dev
  rabbitmq:
    host: ${rmq.asso.host}
    virtual-host: ${rmq.asso.virtual-host}
    port: ${rmq.asso.port}
    username: ${rmq.asso.username}
    password: ${rmq.asso.password}
  datasource:
    driver-class-name: ${db.asso.driverclass}
    url: ${db.asso.url}
    username: ${db.asso.name}
    password: ${db.asso.pwd}
logging:
  level:
    cn.songlin.mapper : debug